# .github/workflows/maven.yml
name: Build and Deploy

on:
  workflow_dispatch:    # 手动触发
  push:
    branches: [ main ]  # 推送时自动触发

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Maven 打包（跳过测试）
      - name: Build with Maven
        env:
          JAVA_HOME: /opt/sdkenvironment/jdk-17.0.12
        run: /usr/local/apache-maven-3.8.9/bin/mvn clean package -DskipTests

      # 4. 上传 jar 包到云服务器
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/*.jar"
          target: "/app/cystrixblog/"

      # 5. SSH 登录服务器，重启应用
      - name: Restart application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 停止旧进程
            pid=$(pgrep -f "cystrixblog")
            if [ -n "$pid" ]; then
              echo "Stopping old process: $pid"
              kill $pid
              sleep 3
            fi

            # 启动新进程
            cd /app/cystrixblog
            nohup java -Dspring.profiles.active=${{ secrets.SPRING_PROFILES_ACTIVE}} -Dspring.cloud.nacos.config.username=${{secrets.SPRING_CLOUD_NACOS_CONFIG_NAME}} -Dspring.cloud.nacos.config.password=${{secrets.SPRING_CLOUD_NACOS_CONFIG_PASSWORD}} -Dspring.cloud.nacos.config.namespace=${{secrets.SPRING_CLOUD_NACOS_CONFIG_NAMESPACE}} -Dspring.cloud.nacos.config.server-addr=${{secrets.SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR}} -Dtomcat.port=${{secrets.TOMCAT_PORT}} -DIP_TOKEN=${{secrets.IP_TOKEN}} -DREDIS_PWD=${{secrets.REDIS_PWD}} -DMAIL_USER=${{secrets.MAIL_USER}} -DMAIL_PWD=${{secrets.MAIL_PWD}} -DDB_USER=${{secrets.DB_USER}} -DDB_PWD=${{secrets.DB_PWD}} -DPRIVATE_KEY=${{secrets.PRIVATE_KEY}} -DIMG_PATH=${{secrets.IMG_PATH}} -DCOVER_PATH=${{secrets.COVER_PATH}} -jar *.jar > app.${{ secrets.TOMCAT_PORT}}.log 2>&1 &
            APP_PID=$!
            echo "Application started, port: ${{secrets.TOMCAT_PORT}} pid: $APP_PID"
